//TODO: MAJOR

//TODO: MINOR
// ADD NOTIFICATIONS IN SOME PLACES
// APPLY NON SENSITIVE EMAIL DURING LOGIN REGISTER (TO LOWER CASE)
// ADD TYPE RELATED TRANSLATIONS
// ADD SHARE EVENT BUTTON

//TODO: AFTER MVP
// CREATE SIDEBAR WITH DATA (MARKERS)
// ADD LOCALE SELECT + CURRENCY CHANGE
// CONSIDER MIGRATION TO @vis.gl/react-google-maps or Migrate from Marker to Advanced Marker

//TODO: BLOCKED
// CONSIDER DATE_FNS DELETION - for now impossible because of date picker locale (month names translations) ;/
