//TODO: LIST
// Migrate from Marker to Advanced Marker
// CONSIDER MIGRATION TO @vis.gl/react-google-maps

//TODO: MILESTONES
//MAP:
// - DISPLAY DATA ON MAP (MARKERS)
// - CREATE SIDEBAR WITH DATA (MARKERS)

//ADD EVENTS:
// - ADD MATCH CATEGORY

// LOGIN/REGISTER/RESET-PASSWORD PAGES (AUTH FLOW)
// CONTACT PAGE
// COOPERATION PAGE
// 404 PAGE
// BACK BUTTON

//i18n
