//TODO: MAJOR
// ADD POSSIBILITY TO ADD MULTIPLE LOCATIONS TO EVENT
// PRICE RANGE
// REACT QUERY + CACHING
// CONSIDER DATE_FNS DELETION

//TODO: MINOR
// REMOVE BARREL IMPORTS
// CONSIDER MIGRATION TO @vis.gl/react-google-maps or Migrate from Marker to Advanced Marker
// ADD TYPE RELATED TRANSLATIONS
// METATAGS IMPROVEMENTS
// STATUTE AND PRIVACY POLICY PAGES
// CREATE SIDEBAR WITH DATA (MARKERS)
// LOGIN/REGISTER/RESET-PASSWORD PAGES (AUTH FLOW)
