//TODO: MAJOR
// FEMALE TYPE
// PRICE RANGE

//TODO: MINOR
// METATAGS, ALTERNATE LINKS, CANONICALS - IMPROVEMENTS
// ADD NOTIFICATIONS IN SOME PLACES
// ADD IMPROVE ESLINT WITH NO USED VARIABLES
// APPLY NON SENSITIVE EMAIL DURING LOGIN REGISTER (TO LOWER CASE)
// ADD LOGOUT ICON IN MAIN MENU
// ADD TYPE RELATED TRANSLATIONS

//TODO: AFTER MVP
// CREATE SIDEBAR WITH DATA (MARKERS)
// CONSIDER MIGRATION TO @vis.gl/react-google-maps or Migrate from Marker to Advanced Marker

//TODO: BLOCKED
// CONSIDER DATE_FNS DELETION - for now impossible because of date picker locale (month names translations) ;/
